import turtle

screen = turtle.Screen()
screen.setup(500, 500)
screen.bgcolor("tan")
t = turtle.Turtle()

t.penup()
t.goto(0,100)
t.pendown()
t.write("About me", font=("arial", 30, "bold"), align="center")


round=input("Press enter to continue:")
t.clear()
screen.bgcolor("red")

#Fav food
t.penup()
t.goto(-100,200)
t.pendown()
t.write("Fav Food", font=("arial", 30, "bold"), align="center")



t.penup()
t.goto(70,100)
t.pendown()
t.write("Taco Bell", font=("arial", 30, "bold"), align="center")

t.penup()
t.goto(70,-100)
t.pendown()
t.write("Fries", font=("arial", 30, "bold"), align="center")


t.penup()
t.goto(-70,-100)
t.pendown()
t.write("Cheetos", font=("arial", 30, "bold"), align="center")
t.penup()
t.goto(-70,-150)
t.pendown()
screen.addshape('food1.gif'
                '')
t.shape("food1.gif")
t.stamp()
t.penup()
t.goto(70,-150)
t.pendown()
screen.addshape('food2.gif')
t.shape("food2.gif")
t.stamp()
t.penup()
t.goto(70,25)
t.pendown()
screen.addshape('food3.gif')
t.shape("food3.gif")
t.stamp()

round=input("Press enter to continue:")
t.clear()
screen.bgcolor("hot pink")

#hobbies
t.penup()
t.goto(70,100)
t.pendown()
t.write("Basketball", font=("arial", 30, "bold"), align="center")
t.penup()
t.goto(0,-100)
t.pendown()
screen.addshape('hoop.gif')
t.shape("hoop.gif")
t.stamp()
t.penup()
t.goto(-70,100)
t.pendown()
t.write("Swimming", font=("arial", 30, "bold"), align="center")
t.penup()
t.goto(70,-100)
t.pendown()
screen.addshape('pool.gif')
t.shape("pool.gif")
t.stamp()
t.penup()
t.goto(-70,-100)
t.pendown()
t.write("Biking", font=("arial", 30, "bold"), align="center")
t.penup()
t.goto(-200,100)
t.pendown()
screen.addshape('bike.gif')
t.shape("bike.gif")
t.stamp()

t.penup()
t.goto(250,-100)
t.pendown()
t.write("Soccer", font=("arial", 30, "bold"), align="center")
t.penup()
t.goto(200,-200)
t.pendown()
screen.addshape('goal.gif')
t.shape("goal.gif")
t.stamp()


round=input("Press enter to continue:")
t.clear()
screen.bgcolor("purple")

t.penup()
t.goto(-100,200)
t.pendown()
t.write("Fav Movie", font=("arial", 30, "bold"), align="center")

t.penup()
t.goto(-100,100)
t.pendown()
t.write("Home", font=("arial", 30, "bold"), align="center")
t.penup()
t.goto(-200,-100)
t.pendown()
screen.addshape('home.gif')
t.shape("home.gif")
t.stamp()

round=input("Press enter to continue:")
t.clear()
screen.bgcolor("navy blue")

t.penup()
t.goto(100,100)
t.pendown()
t.write("Favorite Sport", font=("arial", 30, "bold"), align="center")
t.penup()
t.goto(0,-100)
t.pendown()
screen.addshape('hoop.gif')
t.shape("hoop.gif")
t.stamp()

t = turtle.Turtle()
turtle.done()



